### ISSUE TITLE
Can't use /scanarena even have used /create

### ISSUE THREAD

**Issue by MyBlueHorizon** [Ayman-Isam/HungerGames#1]
The arena region us not defined in the config.
/create didn't take effort.

**Comment by cantankerous-ally** [comment]
Did you first use /select to select the arena? If the issue still persists, can you maybe share a screenshot or the exact message that you get when you do /create?

**Comment by MyBlueHorizon** [comment]
![图片](https://github.com/cantankerous-ally/Hunger-Games/assets/20754543/4def4d16-73e9-43e8-b418-39e580d63bd3)

**Comment by MyBlueHorizon** [comment]
I use /select frist,
then follow https://github.com/cantankerous-ally/Hunger-Games/wiki/Setup to select block,
then use /create
It told me it has been saved to arena.yml, but the files is empty.(only "arena: []" in it)

Could you share me an example of "arena.yml", so that I can modify the value to use.

**Comment by cantankerous-ally** [comment]
I was just able to reproduce the bug. I've done a fix for that and the latest commit should have the fix for 1.20.4. I'll release the fix for other versions soon. If you're using 1.20.4, you can just replace the mod. If not, this is how the arena.yml should be formatted like.

```Yaml

arena: []
region:
  world: world
  pos1:
    x: 92.0
    y: 58.0
    z: -10.0
  pos2:
    x: 79.0
    y: 51.0
    z: -1.0

```

**Comment by MyBlueHorizon** [comment]
thank you

**Comment by cantankerous-ally** [comment]
No worries
