### ISSUE TITLE
 [Feature request] Deathmatch

### ISSUE THREAD

**Issue by GeekCornerGH** [Ayman-Isam/HungerGames#11]
Basically something like [this](https://youtu.be/Dc241AfeWiQ?t=575), teleport all players in some arena after some time, for the final fight. Probably the only thing missing for this plugin. Thanks for the hard work.

**Comment by Ayman-Isam** [comment]
Wow, I'm so sorry, I looked at your issue but I completely forgot to answer this. I'm having a hard time finding a reason why the deathmatch system would be better than the current system since the world border shrinks close enough that it's a deathmatch anyway

**Comment by GeekCornerGH** [comment]
I think this is up to personal preference, some players may want to have a simple tp instead of a shrinking portal

**Comment by Ayman-Isam** [comment]
Hmm I understand your request, but I haven't had any other requests similar to this, if more people want this feature I'll think about adding it but at the currently I have more features that I'm currently working on I don't really have enough time to add every feature. Thank you for your suggestion though.
