### ISSUE TITLE
Every world is marked as arena

### ISSUE THREAD

**Issue by DuckManZach** [Ayman-Isam/HungerGames#12]
This plugin does too much for someone who wants to have a server not completely dedicated to survival games. You should make a system where not every world is added to the config by default, or gives hungergames tips unless its specified in the config.

**Comment by Ayman-Isam** [comment]
Thanks for the feedback. For the first suggestion, having people add all the worlds to hungerGames could make it less intuitive but I'll add a config option to exclude worlds. For the second one, I'll add the config option too

**Comment by DuckManZach** [comment]
I think a better option would be to have a whitelist, or to only initialize everything once an arena is created manually in the world.

**Comment by Ayman-Isam** [comment]
Most people who install my plugins use it to just play HungerGames so adding a whitelist will add another step that everyone would have to do so it just makes it harder for most people so but thanks for the suggestion

**Comment by Ayman-Isam** [comment]
Btw the latest version supports ignored-worlds
