### ISSUE TITLE
Player Count Bugs

### ISSUE THREAD

**Issue by ac15CR** [Ayman-Isam/HungerGames#15]
The player count completely bugs when using /hg map {mapname} and will teleport and join all the current players in the lobby but these "joins" won't actually count towards the player count and the game will not start due to the players not registering as in the game (running /hg start or waiting for automatic start).

The player count also double counts players when using /hg join {mapname}.
![image](https://github.com/user-attachments/assets/dd1d400f-3b22-4b35-964a-8961695c4efd)
![image](https://github.com/user-attachments/assets/3f19c251-6127-4f49-8b28-c9dd83999bc0)
This will completely break the count but it does seem to fix itself if you later leave then join using a sign.

**Comment by Ayman-Isam** [comment]
Fixed the bug, commit with the fix will be pushed soon
