### ISSUE TITLE
reloadconfig not applying new config changes

### ISSUE THREAD

**Issue by ac15CR** [Ayman-Isam/HungerGames#16]
When you update a config value (like vote for example), then use /hg reloadconfig, it doesn't apply the new config.

Ex:
Vote is off for a map.
You go into the config file for that map and turn vote on.
You run /hg reloadconfig with a response of success.
You join the map.
Vote is still off.

The only way I've been able to get the config to fully reload is by reloading/restarting the entire server.

**Comment by Ayman-Isam** [comment]
Fixed with latest commit
