### ISSUE TITLE
Network Protocol Error on 1.21

### ISSUE THREAD

**Issue by nickswink** [Ayman-Isam/HungerGames#19]
Testing on 1.21 & 1.21.1

I am testing on a paper server with Essentials and worldedit installed. When it is only one person in the server the game starts normally with `/hg start`.

But when two people are in the game, after doing `/hg start` the clients are kicked with the message `Network Protocol Error`.

**Comment by Ayman-Isam** [comment]
Hmm, can you check if you have the packetevents option enabled in the config?

**Comment by Ayman-Isam** [comment]
Can you also check if you're running the latest version of the plugin, 1.7.3?

**Comment by nickswink** [comment]
Used updated version fixed this
