### ISSUE TITLE
Left Click Sign with [Join] Can't Work

### ISSUE THREAD

**Issue by MyBlueHorizon** [Ayman-Isam/HungerGames#2]

**Comment by cantankerous-ally** [comment]
does your sign say [Join] including the brackets?

**Comment by MyBlueHorizon** [comment]
Yes
Right Click is ok.

**Comment by MyBlueHorizon** [comment]
Another problem, player who don't have OP permission sometime can't click sign to join.

**Comment by cantankerous-ally** [comment]
Oh wait I misread your message, I'll enable left clicking the sign too. For the non-OP players not being able to join, it's because of spawn protection. I've updated the wiki so that people know to disable spawn protection.

**Comment by MyBlueHorizon** [comment]
Thank you.

**Comment by cantankerous-ally** [comment]
No worries
