### ISSUE TITLE
Loot Generation not woirking

### ISSUE THREAD

**Issue by SolarAccelerant** [Ayman-Isam/HungerGames#21]
So, Im currently creating a hunger games server for me and my friends but every time I change the loot generation for a specific map (I dont think this is important but it goes above 9 bytes) then when I try to enter a match, the chests just don't fill up at all.

**Comment by Ayman-Isam** [comment]
Sorry for the late response, have you tried doing /hg scanarena? This command scans the locations of chests and it fills the chests based on those locations.

**Comment by Ayman-Isam** [comment]
Closing issue, user hasn't responded in a month
