### ISSUE TITLE
When Game is Not Really Ready, Player Can Move and Will Take Some Error.

### ISSUE THREAD

**Issue by MyBlueHorizon** [Ayman-Isam/HungerGames#3]
> [20:38:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-409 (MC: 1.20.4) ---
> 
> [20:38:51] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
> [20:38:51] [Paper Watchdog Thread/ERROR]: ------------------------------
> [20:38:51] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [20:38:51] [Paper Watchdog Thread/ERROR]: [ChunkTaskScheduler] Chunk wait task info below: 
> [20:38:51] [Paper Watchdog Thread/ERROR]: [ChunkTaskScheduler] Chunk wait: [( -9,6) in 'world']
> [20:38:51] [Paper Watchdog Thread/ERROR]: [ChunkTaskScheduler] Chunk holder: NewChunkHolder{world=world, chunkX=-9, chunkZ=6, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=null,status=null}, currentGenStatus=null, requestedGenStatus=minecraft:full, generationTask=ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkLoadTask, for world: world, chunk: (-9,6), hashcode: 753833982, priority: BLOCKING, status: minecraft:empty, scheduled: true}, generationTaskStatus=minecraft:empty, priority=BLOCKING, priorityLocked=false, neighbourRequestedPriority=IDLE, effective_priority=BLOCKING, oldTicketLevel=33, currentTicketLevel=33, totalNeighboursUsingThisChunk=1, fullNeighbourChunksLoadedBitset=3264247, chunkStatusRaw=0, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}
> [20:38:51] [Paper Watchdog Thread/ERROR]: ------------------------------
> [20:38:51] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
> [20:38:51] [Paper Watchdog Thread/ERROR]: 	PID: 27 | Suspended: false | Native: false | State: RUNNABLE
> [20:38:51] [Paper Watchdog Thread/ERROR]: 	Stack:
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.9/java.lang.Thread.yield(Native Method)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:147)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:282)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.getChunk(Level.java:889)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.getBlockState(Level.java:1168)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getType(CraftBlock.java:223)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		HungerGames 1.2.3-1.20.4.jar//me.cantankerousally.hungergames.commands.ChestRefillCommand.onCommand(ChestRefillCommand.java:359)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		HungerGames 1.2.3-1.20.4.jar//me.cantankerousally.hungergames.handler.GameHandler.startGame(GameHandler.java:202)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		HungerGames 1.2.3-1.20.4.jar//me.cantankerousally.hungergames.commands.StartGameCommand.lambda$onCommand$0(StartGameCommand.java:88)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		HungerGames 1.2.3-1.20.4.jar//me.cantankerousally.hungergames.commands.StartGameCommand$$Lambda$9462/0x00000248c7f977c0.run(Unknown Source)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6218/0x00000248c7b87c78.run(Unknown Source)
> [20:38:51] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
> [20:38:51] [Paper Watchdog Thread/ERROR]: ------------------------------
> [20:38:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [20:38:51] [Paper Watchdog Thread/ERROR]: ------------------------------

**Comment by MyBlueHorizon** [comment]
Player can try to open Ender Chest when every thing not ready, then the error will appear.
There is a few seconds when player can move and game really start.

**Comment by cantankerous-ally** [comment]
Hmm, how many chests do you have in your map? I just need an estimate

**Comment by cantankerous-ally** [comment]
Also could you share the map with me so that I can see if I can reproduce the issue.

**Comment by MyBlueHorizon** [comment]
Just the map mention in wiki.
https://www.planetminecraft.com/project/seacliff-sg-a-24-player-hunger-games-survival-games-map-created-by-berserker/
I think maybe I set the area too big.(300, 0, 300 to -300, 127, -300)

**Comment by cantankerous-ally** [comment]
Hmm this is weird, I'm doing primary testing on this map, my arena is bigger than this and I don't have the message. The message is not really an error, more like a paper warning, the server is freezing because the command is taking too long to execute. Could you provide the specs of hardware you're running the server on, the model of the CPU and the amount of ram allocated to Minecraft would be enough. Also is the error happening after you do /scanarena or after the game starts and the chestrefill command starts running?

**Comment by MyBlueHorizon** [comment]
Intel Xeon Platinum run at 2.5Ghz, but only two cores.
2GB RAM and 1280MB allocated to Minecraft.
Actually,between "1 second left!" and "Chests have been refilled!"
And "/scanarena" take too long time.

**Comment by MyBlueHorizon** [comment]
emm, It seem be solve and I don't know what happened or changed.

**Comment by cantankerous-ally** [comment]
That's nice since I wasn't able to replicate the lag after the game started. I was however able to replicate scanarena taking too long. I'll see what I can do.

**Comment by MyBlueHorizon** [comment]
The wiki say scanarena will take 30 seconds, so I just wait about 2 minutes and think it is enough. (Actually, when I read the sources code, I notice it should have an message to say it finished (Chest locations have been saved! ) . But I never see it and start the game. So, think maybe it is reason.

However, I can't replicate again, maybe the plugin under a strange stage when it happened.

Update: It be replicated. The reason is right. I delect chest-locations file and run scanarena again, about 3 minutes ago, I run start and it happened. After server crashed, the file of chest-locations be saved. So the next time I start server, nothing happened and everything is ok.

**Comment by cantankerous-ally** [comment]
Hmm, I've done a fix for that, previously, the scanarena process would run in a seperate thread to the main one which meant you could interact with the server while it was running. But it also meant that it would take a lot of time to run. Now I changed it to use the main thread which is a lot faster, now it takes 10-15 seconds but the server does not work during the time. I think the reason why you got the error was that the scanarena did not finish running due to it being super slow and when you do /start it creates the error. If you check the latest commit, there is the version for 1.20.4. I'll update the plugins later, I would have to compile them for each version and upload accordingly.

**Comment by cantankerous-ally** [comment]
BTW thank you sooooo much for making the plugin better for other players.

**Comment by MyBlueHorizon** [comment]
Thank you for your developing, too.
By the way, do you have a plan to add localization support, such as put strings in language file, so that others can contribute to translate the plugin to more language.

**Comment by MyBlueHorizon** [comment]
Thank you for your developing, too.
By the way, do you have a plan to add localization support, such as put strings in language file, so that others can contribute to translate the plugin to more language.

**Comment by cantankerous-ally** [comment]
Hmm haven't thought about this yet but this is a great idea. I'll look into that sometime in the near future.

**Comment by Ayman-Isam** [comment]
Hey, my latest commit has a version of the plugin which adds support for multiple languages. In the lang folder in hungergames, currently there's six languages. If you want to add more languages, just create a new file, naming it using [this](https://minecraft.wiki/w/Language) conversion. Otherwise you can edit the text in the files since I use AI for translation and it isn't that good. If you have any suggestions for better translations, specially for chinese, it would be wonderful if you could let me know.
