### ISSUE TITLE
Supply drops causes game crash

### ISSUE THREAD

**Issue by pjindras** [Ayman-Isam/HungerGames#8]
Hello, I instaled plugin and set the arena as it is described in Wiki, but when the supply drop should time, in this second the whole server stucks and game crashes.

Log: https://mclo.gs/k4emNES

It makes server out of memorry (memory is ok till air drop comes)

**Comment by Ayman-Isam** [comment]
Hmm could you please let me know which version of the plugin you're using? Could you also send me contents of arena.yml and let me know what CPU you're using and how much ram the server has?

**Comment by pjindras** [comment]
We are using amd ryzen 9 7900, server has 6gb ram, but I can set set how much I want, just for testing purpose, I set it to 6.

Arena.yml content: https://mclo.gs/1Od2T3F

**Comment by pjindras** [comment]
I am using version 1.5.0

**Comment by Ayman-Isam** [comment]
Hmm looking at your setup it seems that the issue isn't the size of the arena, I have a ryzen 7 5800 and 4gb allocated and it doesn't lag for me. I'll give you a newer version of my plugin that I've been working on, you can try and see if that works, I've rewrote the supplydrop system in this version. Just let me know if you encounter any more issues with the new version.

**Comment by pjindras** [comment]
ok, thank you

**Comment by Ayman-Isam** [comment]
https://github.com/Ayman-Isam/Hunger-Games/blob/main/build/libs/HungerGames-1.5.0-1.20.jar

Here's the link to the file, let me know if it works, you shouldn't have to do much to set up since it still uses the same config settings

**Comment by pjindras** [comment]
now it spawns drops, but out of map, in void somewhere far away

![image](https://github.com/Ayman-Isam/Hunger-Games/assets/45400186/f4c7b64c-6e72-4596-aa10-64f8167b82b7)

**Comment by Ayman-Isam** [comment]
Oh I forgot to fix that, is your map round, as in there are ways to go to the void in the map?

**Comment by pjindras** [comment]
yes, it is only void with the pasted map, but there is barrier, so player cannot go into the void

**Comment by Ayman-Isam** [comment]
Okay, go to the link again, https://github.com/Ayman-Isam/Hunger-Games/blob/main/build/libs/HungerGames-1.5.0-1.20.jar I've updated the file, the new version should fix it

**Comment by pjindras** [comment]
Now it still causes the issue:
https://paste.gg/p/anonymous/dc9d58e6bef146059d494695041d5b2a

**Comment by Ayman-Isam** [comment]
Is there any way I could connect to your server and see the map so that I can see the map and the issue, if you don't want to share your server here you can also email me the ip

**Comment by pjindras** [comment]
yes, no problem, join play.fenixcraft.cz and I will be waiting on lobby, if there was any problem with connection, let me know

**Comment by Ayman-Isam** [comment]
![image](https://github.com/Ayman-Isam/Hunger-Games/assets/94015277/ff570b1b-9d81-4176-b436-8eb574f36fc9)
I'm having some issues related to logging in

**Comment by pjindras** [comment]
try it now, it had blacklist for non EU ip adresses

**Comment by Ayman-Isam** [comment]
My IGN is cantankerousally

**Comment by pjindras** [comment]
ok, I sent you pm, please go /server sg1 there i have Hunger games pl

**Comment by Ayman-Isam** [comment]
I found the issue, it's cause you haven't set the world border size to a reasonable amount, it's trying to place supplydrops but it keeps finding the void cause it can't find non void blocks since the border is too big. Do /hg border and set size

**Comment by Ayman-Isam** [comment]
Issue was the border was set too far away which caused the plugin to look for too many blocks causing it to throw exceptions

**Comment by pjindras** [comment]
I found one more issue, it keeps the shulkers from the drops on the map after game ends. @Ayman-Isam

**Comment by Ayman-Isam** [comment]
Hmm that's really weird, it's supposed to remove all of them after the game ends. I'm sending you this file with debugging information, please check your console and send me all the Hungergames STDOUT Messages that you see, here's a sample one

[20:28:30 INFO]: [HungerGames] [STDOUT]  §CantankerousAlly

You should be seeing the message "Remove Shulkers Called"
and the message "Shulker Found"

[HungerGames-1.5.0-1.20.zip](https://github.com/user-attachments/files/15518254/HungerGames-1.5.0-1.20.zip)

**Comment by pjindras** [comment]
I think its ok, it happend only once, than I couldnt reply the issue again.
